load("//bazel:ray.bzl", "ray_cc_library")

ray_cc_library(
    name = "gcs_lease_manager",
    srcs = [
        "gcs_lease_manager.cc",
    ],
    hdrs = [
        "gcs_lease_manager.h",
        "lease_info.h",
    ],
    deps = [
        "//src/ray/asio:instrumented_io_context",
        "//src/ray/asio:periodical_runner_interface",
        "//src/ray/common:id",
        "//src/ray/common:lease",
        "//src/ray/core_worker_rpc_client:core_worker_client_pool",
        "//src/ray/gcs:gcs_node_manager",
        "//src/ray/gcs:grpc_service_interfaces",
        "//src/ray/protobuf:gcs_service_cc_proto",
        "//src/ray/ray_syncer",
        "//src/ray/raylet/scheduling:cluster_lease_manager",
        "//src/ray/util:clock",
        "//src/ray/util:counter_map",
        "//src/ray/util:logging",
    ],
)
